export const en = {
  preSession: {
    calm: 'One minute. Breathe with me.',
    hype: 'Lock in. One clean minute.',
  },
  phase: {
    inhale: 'Inhale',
    holdIn: 'Hold',
    exhale: 'Exhale',
    holdOut: 'Hold',
  },
  postSession: {
    calm: 'Nice. Back when you\'re ready.',
    short: 'Welcome back.',
  },
  streakInc: (n: number) => `${n} session${n === 1 ? '' : 's'} today`,
  skipPrompt: 'Want to skip today?',
  crisisLink: 'Need real support? Tap here.',
  overlay: {
    exit: 'Exit',
    skipToday: 'Skip today',
    yes: 'Yes',
    no: 'No',
    done: 'Done',
    moodPrompt: 'How do you feel?',
    pausedFor30: 'Paused for 30 minutes',
  },
  mood: {
    calm: 'Calm',
    good: 'Good',
    neutral: 'Neutral',
    stressed: 'Stressed',
  },
  popup: {
    on: 'On',
    off: 'Off',
    pause30: 'Pause 30 min',
    pause2h: 'Pause 2 hours',
    pauseToday: 'Pause today',
    resume: 'Resume',
    nextSession: 'Next session',
    sessionsToday: (n: number) => `${n} session${n === 1 ? '' : 's'} today`,
    snoozedUntil: (time: string) => `Paused until ${time}`,
    confirmOff: 'Turn Breath Break off?',
  },
  options: {
    title: 'Breath Break Settings',
    sites: 'Sites',
    frequency: 'Frequency',
    character: 'Character',
    theme: 'Theme',
    save: 'Save',
    addSite: 'Add site',
    removeSite: 'Remove',
    audio: 'Audio',
    audioMode: 'Sound',
    musicTrack: 'Music track',
    audioModes: {
      silent: 'Silent',
      chime: 'Chime',
      music: 'Ambient music',
      voice_calm: 'Calm voice',
      voice_hype: 'Hype voice',
      voice_savage: 'Savage voice (Premium)',
      voice_custom: 'Custom voice (Premium)',
    },
    musicTracks: {
      lofi_rain: 'Lo-fi rain',
      forest: 'Forest',
      tibetan_bowl: 'Tibetan bowl',
    },
    paywallTitle: 'Premium feature',
    paywallBody: 'Savage and custom voices are coming soon to Breath Break Premium.',
    paywallCta: 'Join the waitlist',
  },
};

export type CopyKeys = typeof en;
