import type { CopyKeys } from './en';

export const es: CopyKeys = {
  preSession: {
    calm: 'Un minuto. Respira conmigo.',
    hype: 'Concéntrate. Un minuto limpio.',
  },
  phase: {
    inhale: 'Inhala',
    holdIn: 'Mantén',
    exhale: 'Exhala',
    holdOut: 'Mantén',
  },
  postSession: {
    calm: 'Bien hecho. Vuelve cuando estés listo.',
    short: 'Bienvenido de nuevo.',
  },
  streakInc: (n: number) => `${n} ${n === 1 ? 'sesión' : 'sesiones'} hoy`,
  skipPrompt: '¿Quieres saltar hoy?',
  crisisLink: '¿Necesitas apoyo? Toca aquí.',
  overlay: {
    exit: 'Salir',
    skipToday: 'Saltar hoy',
    yes: 'Sí',
    no: 'No',
    done: 'Listo',
    moodPrompt: '¿Cómo te sientes?',
    pausedFor30: 'Pausado 30 minutos',
  },
  mood: {
    calm: 'Tranquilo',
    good: 'Bien',
    neutral: 'Neutral',
    stressed: 'Estresado',
  },
  popup: {
    on: 'Activo',
    off: 'Inactivo',
    pause30: 'Pausar 30 min',
    pause2h: 'Pausar 2 horas',
    pauseToday: 'Pausar hoy',
    resume: 'Reanudar',
    nextSession: 'Próxima sesión',
    sessionsToday: (n: number) => `${n} ${n === 1 ? 'sesión' : 'sesiones'} hoy`,
    snoozedUntil: (time: string) => `Pausado hasta ${time}`,
    confirmOff: '¿Desactivar Breath Break?',
  },
  options: {
    title: 'Configuración de Breath Break',
    sites: 'Sitios',
    frequency: 'Frecuencia',
    character: 'Personaje',
    theme: 'Tema',
    save: 'Guardar',
    addSite: 'Añadir sitio',
    removeSite: 'Eliminar',
    audio: 'Audio',
    audioMode: 'Sonido',
    musicTrack: 'Pista de música',
    audioModes: {
      silent: 'Silencio',
      chime: 'Campanilla',
      music: 'Música ambiental',
      voice_calm: 'Voz tranquila',
      voice_hype: 'Voz motivadora',
      voice_savage: 'Voz atrevida (Premium)',
      voice_custom: 'Voz personalizada (Premium)',
    },
    musicTracks: {
      lofi_rain: 'Lo-fi con lluvia',
      forest: 'Bosque',
      tibetan_bowl: 'Cuenco tibetano',
    },
    paywallTitle: 'Función Premium',
    paywallBody: 'Las voces atrevida y personalizada estarán disponibles en Breath Break Premium.',
    paywallCta: 'Unirse a la lista de espera',
  },
};
