// Hindi (Devanagari) copy — wave 2 launch stub.
// All keys must match the shape of `en` in en.ts.
export const hi = {
  preSession: {
    calm: 'एक मिनट। मेरे साथ सांस लो।',
    hype: 'फोकस करो। एक साफ़ मिनट।',
  },
  phase: {
    inhale: 'सांस लो',
    holdIn: 'रोको',
    exhale: 'छोड़ो',
    holdOut: 'रोको',
  },
  postSession: {
    calm: 'बढ़िया। जब तैयार हो वापस आओ।',
    short: 'स्वागत है।',
  },
  streakInc: (n: number) => `आज ${n} सत्र`,
  skipPrompt: 'आज छोड़ना चाहते हो?',
  crisisLink: 'मदद चाहिए? यहाँ दबाओ।',
  overlay: {
    exit: 'बाहर',
    skipToday: 'आज छोड़ो',
    yes: 'हाँ',
    no: 'नहीं',
    done: 'हो गया',
    moodPrompt: 'अभी कैसा महसूस हो रहा है?',
    pausedFor30: '30 मिनट के लिए रुका',
  },
  mood: {
    calm: 'शांत',
    good: 'अच्छा',
    neutral: 'ठीक',
    stressed: 'तनाव',
  },
  popup: {
    on: 'चालू',
    off: 'बंद',
    pause30: '30 मिनट रोको',
    pause2h: '2 घंटे रोको',
    pauseToday: 'आज के लिए रोको',
    resume: 'फिर शुरू करो',
    nextSession: 'अगला सत्र',
    sessionsToday: (n: number) => `आज ${n} सत्र`,
    snoozedUntil: (time: string) => `${time} तक रुका`,
    confirmOff: 'Breath Break बंद करें?',
  },
  options: {
    title: 'Breath Break सेटिंग्स',
    sites: 'साइटें',
    frequency: 'आवृत्ति',
    character: 'किरदार',
    theme: 'थीम',
    save: 'सहेजें',
    addSite: 'साइट जोड़ें',
    removeSite: 'हटाएं',
    audio: 'ऑडियो',
    audioMode: 'आवाज़',
    musicTrack: 'संगीत',
    audioModes: {
      silent: 'चुप',
      chime: 'घंटी',
      music: 'संगीत',
      voice_calm: 'शांत आवाज़',
      voice_hype: 'उत्साही आवाज़',
      voice_savage: 'तीखी आवाज़ (प्रीमियम)',
      voice_custom: 'कस्टम आवाज़ (प्रीमियम)',
    },
    musicTracks: {
      lofi_rain: 'लो-फाई बारिश',
      forest: 'जंगल',
      tibetan_bowl: 'तिब्बती कटोरा',
    },
    paywallTitle: 'प्रीमियम सुविधा',
    paywallBody: 'यह जल्द आ रही है।',
    paywallCta: 'वेटलिस्ट में जुड़ें',
  },
};
