import type { CopyKeys } from './en';

export const pt: CopyKeys = {
  preSession: {
    calm: 'Um minuto. Respira comigo.',
    hype: 'Foco. Um minuto limpo.',
  },
  phase: {
    inhale: 'Inspire',
    holdIn: 'Segure',
    exhale: 'Expire',
    holdOut: 'Segure',
  },
  postSession: {
    calm: 'Ótimo. Volte quando estiver pronto.',
    short: 'Bem-vindo de volta.',
  },
  streakInc: (n: number) => `${n} ${n === 1 ? 'sessão' : 'sessões'} hoje`,
  skipPrompt: 'Quer pular hoje?',
  crisisLink: 'Precisa de apoio? Toque aqui.',
  overlay: {
    exit: 'Sair',
    skipToday: 'Pular hoje',
    yes: 'Sim',
    no: 'Não',
    done: 'Pronto',
    moodPrompt: 'Como você está se sentindo?',
    pausedFor30: 'Pausado por 30 minutos',
  },
  mood: {
    calm: 'Calmo',
    good: 'Bem',
    neutral: 'Neutro',
    stressed: 'Estressado',
  },
  popup: {
    on: 'Ativo',
    off: 'Inativo',
    pause30: 'Pausar 30 min',
    pause2h: 'Pausar 2 horas',
    pauseToday: 'Pausar hoje',
    resume: 'Retomar',
    nextSession: 'Próxima sessão',
    sessionsToday: (n: number) => `${n} ${n === 1 ? 'sessão' : 'sessões'} hoje`,
    snoozedUntil: (time: string) => `Pausado até ${time}`,
    confirmOff: 'Desativar Breath Break?',
  },
  options: {
    title: 'Configurações do Breath Break',
    sites: 'Sites',
    frequency: 'Frequência',
    character: 'Personagem',
    theme: 'Tema',
    save: 'Salvar',
    addSite: 'Adicionar site',
    removeSite: 'Remover',
    audio: 'Áudio',
    audioMode: 'Som',
    musicTrack: 'Faixa de música',
    audioModes: {
      silent: 'Silencioso',
      chime: 'Sino',
      music: 'Música ambiente',
      voice_calm: 'Voz calma',
      voice_hype: 'Voz animada',
      voice_savage: 'Voz ousada (Premium)',
      voice_custom: 'Voz personalizada (Premium)',
    },
    musicTracks: {
      lofi_rain: 'Lo-fi com chuva',
      forest: 'Floresta',
      tibetan_bowl: 'Tigela tibetana',
    },
    paywallTitle: 'Recurso Premium',
    paywallBody: 'Vozes ousada e personalizada estão chegando ao Breath Break Premium.',
    paywallCta: 'Entrar na lista de espera',
  },
};
